#!/bin/bash

xrandr | grep "VGA1 connected" >> /dev/null
if [ $? -eq 0 ] ; then
echo "VGA is connected, setting up work environment."
fi

xrandr | grep "HDMI1 connected" >> /dev/null
if [ $? -eq 0 ] ; then
echo "HDMI is only connected, setting up home environment."
fi
