#!/bin/bash

#This checks xrandr output to see whether VGA or HDMI is connected. Dependent on that answer, I utilize xrandr to set up the displays with correct resolution, position and rotation.
#Your set up will be different depending on your monitor, resolution and ports. A dev rule would be more efficient, that will come later.
xrandr | grep "VGA-1 connected" >> /dev/null
if [ $? -eq 0 ] ; then
echo "VGA is connected, setting up work environment."
xrandr output VGA-1 --mode 1600x900 --pos 2566x520 --rotate normal --output HDMI-1 --mode 1920x1200 --pos 1366x0 --rotate left --output eDP-1 --primary --mode 1366x768 --pos 0x520 --rotate normal
fi

xrandr | grep "HDMI-1 connected" >> /dev/null
if [ $? -eq 0 ] ; then
echo "HDMI is only connected, setting up home environment."
xrandr --output HDMI1 --mode 2560x1440 --pos 0x0 --rotate normal --output VIRTUAL1 --off --output eDP1 --mode 1366x768 --pos 2560x568 --rotate normal --out    put VGA1 --off
fi

#Below is a personal modification to set up my wallpaper.
#The sleep is to give the computer enough time to make the above changes ensuring the wallpaper is applied to all screens. Without the sleep timer, the wallpapers would not display correctly. 
sleep 5
feh --bg-fill /home/mo/rec/System/Startup/wallpaper.jpg

#Note: Keep in mind this is built with i3 window manager in mind. 
